import Head from 'next/head'
import LocationContextProvider from '../context/Location'
import App from './App'

export default function Home() {

  return (
    <LocationContextProvider>
      {/* <WeatherProvider> */}
        <div >
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta httpEquiv='Content-Security-Policy' content='upgrade-insecure-requests' />
            <link rel="icon" href="/favicon.ico" />
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous"/>
          </Head>

          <App />

        </div>
      {/* </WeatherProvider> */}
    </LocationContextProvider>
  )
}
